name: Metrics
on:
  schedule: [{cron: "*/5 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: schellj/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
