name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/5 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: schellj/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
